# Generated by Django 4.1.5 on 2023-01-15 00:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import src.apps.core.models.photo


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
            ],
            options={
                'verbose_name': 'Имена людей на фото',
                'verbose_name_plural': 'Имена людей на фото',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to=src.apps.core.models.photo.upload_to_user_photo, verbose_name='Фото')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('x', models.FloatField(blank=True, null=True, verbose_name='X координата геолокации')),
                ('y', models.FloatField(blank=True, null=True, verbose_name='Y координата геолокации')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('names', models.ManyToManyField(blank=True, related_name='photos', related_query_name='photos', to='core.photouser', verbose_name='Имена людей на фото')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', related_query_name='photos', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Фото',
            },
        ),
    ]
